// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CSEARCHSERVERSESSIONTRACES_H__
#define __CSEARCHSERVERSESSIONTRACES_H__

#define KOstTraceComponentID 0x2001f6f7

#define CSEARCHSERVERSESSION_CSEARCHSERVERSESSION 0x860009
#define DUP1_CSEARCHSERVERSESSION_CSEARCHSERVERSESSION 0x86000a


#endif

// End of file

