//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

//!  ****************************************************************************
//!  Input for TOCSP - Script-based test harness for OCSP
//!  See \Certman\TOCSP\Commands.cpp for description of commands
//!  This file must be in UNICODE
//!  ****************************************************************************

//!  This script is for OOM testing - it contains a few of the tests in XCert-local.txt

//!  ********** BEGIN XCERT SERVER TESTS **************


START_TESTCASE                SEC-TOCSP-XCERTOOM-0001
//! @SYMTestCaseID            SEC-TOCSP-XCERTOOM-0001
RUN_TEST_STEP                 XCert-oom.ini   SEC-TOCSP-XCERTOOM-0001-0001
END_TESTCASE                  SEC-TOCSP-XCERTOOM-0001

START_TESTCASE                SEC-TOCSP-XCERTOOM-0002
//! @SYMTestCaseID            SEC-TOCSP-XCERTOOM-0002
RUN_TEST_STEP                 XCert-oom.ini   SEC-TOCSP-XCERTOOM-0002-0001
END_TESTCASE                  SEC-TOCSP-XCERTOOM-0002

START_TESTCASE                SEC-TOCSP-XCERTOOM-0003
//! @SYMTestCaseID            SEC-TOCSP-XCERTOOM-0003
RUN_TEST_STEP                 XCert-oom.ini   SEC-TOCSP-XCERTOOM-0003-0001
END_TESTCASE                  SEC-TOCSP-XCERTOOM-0003

START_TESTCASE                SEC-TOCSP-XCERTOOM-0004
//! @SYMTestCaseID            SEC-TOCSP-XCERTOOM-0004
RUN_TEST_STEP                 XCert-oom.ini   SEC-TOCSP-XCERTOOM-0004-0001
END_TESTCASE                  SEC-TOCSP-XCERTOOM-0004