// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __RSEARCHSERVERSESSIONTRACES_H__
#define __RSEARCHSERVERSESSIONTRACES_H__

#define KOstTraceComponentID 0x2001f6fe

#define RSEARCHSERVERSUBSESSION_SEARCHL_ENTRY 0x8a0007
#define RSEARCHSERVERSUBSESSION_SEARCHL_EXIT 0x8a0008
#define RSEARCHSERVERSUBSESSION_SEARCH_ENTRY 0x8a0009
#define RSEARCHSERVERSUBSESSION_SEARCH_EXIT 0x8a000a
#define RSEARCHSERVERSUBSESSION_GETDOCUMENTL_ENTRY 0x8a000b
#define RSEARCHSERVERSUBSESSION_GETDOCUMENT_ENTRY 0x8a000c
#define RSEARCHSERVERSUBSESSION_GETDOCUMENT_EXIT 0x8a000d
#define RSEARCHSERVERSUBSESSION_GETDOCUMENTOBJECTL_ENTRY 0x8a000e
#define RSEARCHSERVERSUBSESSION_GETDOCUMENTOBJECTL_EXIT 0x8a000f
#define RSEARCHSERVERSUBSESSION_UPDATEL 0x860001
#define DUP1_RSEARCHSERVERSUBSESSION_UPDATEL 0x860002
#define RSEARCHSERVERSUBSESSION_SEARCHL 0x86000a


#endif

// End of file

