// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

//////////////////////////////////////////////////////////////////////////////////////
//
// test.script
//
////////////////////////////////////////////////////////////////////////////////////
LOAD_SUITE BURTestServer

PRINT ----------------------------------------------
PRINT  Test Backup Invalid
PRINT ----------------------------------------------
RUN_UTILS DeleteDirectory C:\BackupArchive\
START_TESTCASE MTP-SBE-BACKUPINVALIDIDS-0000
//! @SYMTestCaseID MTP-SBE-BACKUPINVALIDIDS-0000
//! @SYMTestCaseDesc Invalid data owner ID test
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority High
//! @SYMTestActions   Specify an invlid id and try backup it.
//! @SYMTestExpectedResults SBE can't found and do nothing
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestBackup z:\testdata\scripts\sbetestdata\test.ini BACKUP_RESTORE_0050
END_TESTCASE MTP-SBE-BACKUPINVALIDIDS-0000

DELAY 10000

START_TESTCASE MTP-SBE-BACKUPINVALIDDRIVE-0001
//! @SYMTestCaseID MTP-SBE-BACKUPINVALIDDRIVE-0001
//! @SYMTestCaseDesc Invalid drive test
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority High
//! @SYMTestActions   Specify an invalid drive for a data owner to backup
//! @SYMTestExpectedResults SBE backup operation return -1
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestBackup z:\testdata\scripts\sbetestdata\test.ini BACKUP_RESTORE_0060
END_TESTCASE MTP-SBE-BACKUPINVALIDDRIVE-0001

DELAY 10000

RUN_UTILS MkDir c:\private\12345678\
RUN_UTILS CopyFile z:\testdata\scripts\sbetestdata\backup_registration.xml c:\private\12345678\backup_registration.xml
START_TESTCASE MTP-SBE-BACKUPINVALIDDIR-0002
//! @SYMTestCaseID MTP-SBE-BACKUPINVALIDDIR-0002
//! @SYMTestCaseDesc Invalid directory test
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority High
//! @SYMTestActions   Specify an invalid directory for a data owner to backup
//! @SYMTestExpectedResults SBE can't found and do nothing
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestBackup z:\testdata\scripts\sbetestdata\test.ini BACKUP_RESTORE_0070
END_TESTCASE MTP-SBE-BACKUPINVALIDDIR-0002

DELAY 10000

RUN_UTILS DeleteDirectory c:\private\12345678\
RUN_UTILS DeleteDirectory c:\BackupArchive\
RUN_UTILS DeleteDirectory c:\private\0AB7E58F\
RUN_UTILS MkDir c:\private\0AB7E58F\
RUN_UTILS CopyFile  z:\testdata\scripts\sbetestdata\invalidproxymgr.xml c:\private\0AB7E58F\backup_registration.xml
RUN_UTILS MakeReadWrite c:\private\0AB7E58F\backup_registration.xml
START_TESTCASE MTP-SBE-BACKUPINVALIDPROXY-0003
//! @SYMTestCaseID MTP-SBE-BACKUPINVALIDPROXY-0003
//! @SYMTestCaseDesc Invalid proxy manager test
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority High
//! @SYMTestActions   Specify an invalid proxy manager in register file for a data owner to backup
//! @SYMTestExpectedResults SBE can't found and do nothing
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestBackup z:\testdata\scripts\sbetestdata\test.ini BACKUP_RESTORE_0075
END_TESTCASE MTP-SBE-BACKUPINVALIDPROXY-0003

DELAY 10000

RUN_UTILS DeleteDirectory c:\private\0AB7E58F\
RUN_UTILS DeleteDirectory c:\BackupArchive\
RUN_UTILS MkDir c:\private\0AB7E58F\
RUN_UTILS CopyFile  z:\testdata\scripts\sbetestdata\increamenttest.xml c:\private\0AB7E58F\backup_registration.xml
RUN_UTILS CopyFile  z:\sys\bin\esock.dll c:\private\0AB7E58F\needbackup.xml
START_TESTCASE MTP-SBE-BACKUPREADONLY-0004
//! @SYMTestCaseID MTP-SBE-BACKUPREADONLY-0004
//! @SYMTestCaseDesc Test readonly file backup. This case only valid on hardware, on winscw, all file is readable.
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority High
//! @SYMTestActions   Backup a read only file
//! @SYMTestExpectedResults no error
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestBackup z:\testdata\scripts\sbetestdata\test.ini BACKUP_RESTORE_0075
END_TESTCASE MTP-SBE-BACKUPREADONLY-0004

DELAY 10000

START_TESTCASE MTP-SBE-RESTOREREADONLY-0005
//! @SYMTestCaseID MTP-SBE-RESTOREREADONLY-0005
//! @SYMTestCaseDesc Test readonly file restore
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority High
//! @SYMTestActions   Restore a readonly file, but the origin file exist
//! @SYMTestExpectedResults -21
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestRestore z:\testdata\scripts\sbetestdata\test.ini BACKUP_RESTORE_0077
END_TESTCASE MTP-SBE-RESTOREREADONLY-0005
RUN_UTILS DeleteDirectory c:\private\0AB7E58F\

DELAY 10000