// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

//////////////////////////////////////////////////////////////////////////////////////
//
// test_backuppackage.script
// for testing backup datas of installed applications 
//
////////////////////////////////////////////////////////////////////////////////////
LOAD_SUITE BURTestServer

PRINT ----------------------------------------------
PRINT  Test Restore
PRINT ----------------------------------------------
RUN_UTILS DeleteDirectory C:\system\temp\

START_TESTCASE MTP-SBE-RESTOREBACKUPPACKAGE-0000
//! @SYMTestCaseID MTP-SBE-RESTOREBACKUPPACKAGE-0000
//! @SYMTestCaseDesc            Restore big data which owner is install application
//! @SYMPREQ                    PREQ2492
//! @SYMTestStatus              Released  
//! @SYMTestPriority            High
//! @SYMTestActions             Restore executable files and private datas of install application from bakcup file.
//! @SYMTestExpectedResults     1. The executable files are same like after installing application
//!                             2. The name and size of private files are same like after installing application.
//!                             3. The public files don't be restored.  
//! @SYMTestType                CIT
RUN_TEST_STEP 300 BURTestServer TestRestore z:\testdata\scripts\sbetestdata\test.ini PACKAGE_0020
END_TESTCASE MTP-SBE-RESTOREBACKUPPACKAGE-0000

DELAY 10000

START_TESTCASE MTP-SBE-RESTOREBACKUPPACKAGE-0001
//! @SYMTestCaseID MTP-SBE-RESTOREBACKUPPACKAGE-0001
//! @SYMTestCaseDesc            Backup DLLs data which are installed as part of package
//! @SYMPREQ                    PREQ2492
//! @SYMTestStatus              Released
//! @SYMTestPriority            High
//! @SYMTestActions             Restore executable files and private datas of install DLL from bakcup file.
//! @SYMTestExpectedResults     1. The dll files are same like after installing application
//!                             2. The name and size of DLLs are same like after installing application.
//!                             3. The public files don't be restored. 
//! @SYMTestType                CIT
RUN_TEST_STEP 300 BURTestServer TestRestore z:\testdata\scripts\sbetestdata\test.ini PACKAGE_0040
END_TESTCASE MTP-SBE-RESTOREBACKUPPACKAGE-0001

RUN_PROGRAM 900 swiconsole /u /uid 0x8111300b /pkg "big exe for backup" /vendor "Unique Vendor Name" /optimal
RUN_PROGRAM 1000 swiconsole /u /uid 0x81113002 /pkg "tswinocapability" /vendor "Symbian" /optimal

DELAY 10000