// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//


//////////////////////////////////////////////////////////////////////////////////////
//
// test_activebackup.script
//
////////////////////////////////////////////////////////////////////////////////////
LOAD_SUITE BURTestServer

PRINT ----------------------------------------------
PRINT  Test Active Backup
PRINT ----------------------------------------------
RUN_UTILS DeleteDirectory C:\BackupArchive\
START_TESTCASE MTP-SBE-ACTIVEBACKUP-0010
//! @SYMTestCaseID MTP-SBE-ACTIVEBACKUP-0010
//! @SYMTestCaseDesc Do BaseOnly active-backup for three data owners
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority normal
//! @SYMTestActions Do BaseOnly active-backup for three data owners 
//! @SYMTestExpectedResults Backup succeeds
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestBackup z:\testdata\scripts\sbetestdata\test.ini ACTIVE_BACKUP_0010
END_TESTCASE MTP-SBE-ACTIVEBACKUP-0010

DELAY 10000

START_TESTCASE MTP-SBE-ACTIVEBACKUP-0020
//! @SYMTestCaseID MTP-SBE-ACTIVEBACKUP-0020
//! @SYMTestCaseDesc Do Proxy active-backup for specified data owner
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority normal
//! @SYMTestActions Do Proxy active-backup for specified data owner
//! @SYMTestExpectedResults Backup succeeds
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestBackup z:\testdata\scripts\sbetestdata\test.ini ACTIVE_BACKUP_0020
END_TESTCASE MTP-SBE-ACTIVEBACKUP-0020

DELAY 10000

START_TESTCASE MTP-SBE-ACTIVEBACKUP-0030
//! @SYMTestCaseID MTP-SBE-ACTIVEBACKUP-0030
//! @SYMTestCaseDesc Do Incremental active-backup for specified data owner
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority normal
//! @SYMTestActions Do Incremental active-backup for specified data owner
//! @SYMTestExpectedResults Backup succeeds
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestBackup z:\testdata\scripts\sbetestdata\test.ini ACTIVE_BACKUP_0030
END_TESTCASE MTP-SBE-ACTIVEBACKUP-0030

DELAY 10000

START_TESTCASE MTP-SBE-ACTIVEBACKUP-0040
//! @SYMTestCaseID MTP-SBE-ACTIVEBACKUP-0040
//! @SYMTestCaseDesc Do active-backup for a data owner whose executable file is missing
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority normal
//! @SYMTestActions Do active-backup for a data owner whose executable file is missing
//! @SYMTestExpectedResults Backup fails with error code 5
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestBackup z:\testdata\scripts\sbetestdata\test.ini ACTIVE_BACKUP_0040
END_TESTCASE MTP-SBE-ACTIVEBACKUP-0040

DELAY 10000

PRINT ----------------------------------------------
PRINT  Test Active Restore
PRINT ----------------------------------------------

START_TESTCASE MTP-SBE-ACTIVERESTORE-0010
//! @SYMTestCaseID MTP-SBE-ACTIVERESTORE-0010
//! @SYMTestCaseDesc Do BaseOnly active-restore for three data owners
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority normal
//! @SYMTestActions Do BaseOnly active-restore for three data owners  
//! @SYMTestExpectedResults Restore succeeds
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestRestore z:\testdata\scripts\sbetestdata\test.ini ACTIVE_RESTORE_0010
END_TESTCASE MTP-SBE-ACTIVERESTORE-0010

DELAY 10000

START_TESTCASE MTP-SBE-ACTIVERESTORE-0020
//! @SYMTestCaseID MTP-SBE-ACTIVERESTORE-0020
//! @SYMTestCaseDesc Do Proxy active-restore for specified data owner
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority normal
//! @SYMTestActions Do Proxy active-restore for specified data owner  
//! @SYMTestExpectedResults Restore succeeds
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestRestore z:\testdata\scripts\sbetestdata\test.ini ACTIVE_RESTORE_0020
END_TESTCASE MTP-SBE-ACTIVERESTORE-0020

DELAY 10000

START_TESTCASE MTP-SBE-ACTIVERESTORE-0030
//! @SYMTestCaseID MTP-SBE-ACTIVERESTORE-0030
//! @SYMTestCaseDesc Do Incremental active-restore for specified data owner
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority normal
//! @SYMTestActions Do Incremental active-restore for specified data owner  
//! @SYMTestExpectedResults Restore succeeds
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestRestore z:\testdata\scripts\sbetestdata\test.ini ACTIVE_RESTORE_0030
END_TESTCASE MTP-SBE-ACTIVERESTORE-0030

DELAY 10000

START_TESTCASE MTP-SBE-ACTIVERESTORE-0040
//! @SYMTestCaseID MTP-SBE-ACTIVERESTORE-0040
//! @SYMTestCaseDesc Do active-restore for a data owner whose executable file is missing
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority normal
//! @SYMTestActions Do active-restore for a data owner whose executable file is missing 
//! @SYMTestExpectedResults Restore fails with error code 5
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestRestore z:\testdata\scripts\sbetestdata\test.ini ACTIVE_RESTORE_0040
END_TESTCASE MTP-SBE-ACTIVERESTORE-0040

DELAY 10000

PRINT ----------------------------------------------
PRINT  Test Active Backup Async
PRINT ----------------------------------------------
RUN_UTILS DeleteDirectory C:\BackupArchive\
START_TESTCASE MTP-SBE-ACTIVEBACKUP-ASYNC-0010
//! @SYMTestCaseID MTP-SBE-ACTIVEBACKUP-ASYNC-0010
//! @SYMTestCaseDesc Do BaseOnly active-backup for three data owners asynchronously
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority normal
//! @SYMTestActions Do BaseOnly active-backup for three data owners asynchronously
//! @SYMTestExpectedResults Backup succeeds
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestBackupAsync z:\testdata\scripts\sbetestdata\test.ini ACTIVE_BACKUP_0010
END_TESTCASE MTP-SBE-ACTIVEBACKUP-ASYNC-0010

DELAY 10000

START_TESTCASE MTP-SBE-ACTIVEBACKUP-ASYNC-0020
//! @SYMTestCaseID MTP-SBE-ACTIVEBACKUP-ASYNC-0020
//! @SYMTestCaseDesc Do Proxy active-backup for specified data owner asynchronously
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority normal
//! @SYMTestActions Do Proxy active-backup for specified data owner asynchronously
//! @SYMTestExpectedResults Backup succeeds
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestBackupAsync z:\testdata\scripts\sbetestdata\test.ini ACTIVE_BACKUP_0020
END_TESTCASE MTP-SBE-ACTIVEBACKUP-ASYNC-0020

DELAY 10000

START_TESTCASE MTP-SBE-ACTIVEBACKUP-ASYNC-0030
//! @SYMTestCaseID MTP-SBE-ACTIVEBACKUP-ASYNC-0030
//! @SYMTestCaseDesc Do Incremental active-backup for specified data owner asynchronously
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority normal
//! @SYMTestActions Do Incremental active-backup for specified data owner asynchronously 
//! @SYMTestExpectedResults Backup succeeds
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestBackupAsync z:\testdata\scripts\sbetestdata\test.ini ACTIVE_BACKUP_0030
END_TESTCASE MTP-SBE-ACTIVEBACKUP-ASYNC-0030

DELAY 10000

START_TESTCASE MTP-SBE-ACTIVEBACKUP-ASYNC-0040
//! @SYMTestCaseID MTP-SBE-ACTIVEBACKUP-ASYNC-0040
//! @SYMTestCaseDesc Do active-backup asynchronously for a data owner whose executable file is missing
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority normal
//! @SYMTestActions Do active-backup asynchronously for a data owner whose executable file is missing  
//! @SYMTestExpectedResults Backup fails with error code 5
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestBackupAsync z:\testdata\scripts\sbetestdata\test.ini ACTIVE_BACKUP_0040
END_TESTCASE MTP-SBE-ACTIVEBACKUP-ASYNC-0040

DELAY 10000

PRINT ----------------------------------------------
PRINT  Test Active Restore Async
PRINT ----------------------------------------------

START_TESTCASE MTP-SBE-ACTIVERESTORE-ASYNC-0010
//! @SYMTestCaseID MTP-SBE-ACTIVERESTORE-ASYNC-0010
//! @SYMTestCaseDesc Do BaseOnly active-restore for three data owners asynchronously
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority normal
//! @SYMTestActions Do BaseOnly active-restore for three data owners asynchronously
//! @SYMTestExpectedResults Restore succeeds
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestRestoreAsync z:\testdata\scripts\sbetestdata\test.ini ACTIVE_RESTORE_0010
END_TESTCASE MTP-SBE-ACTIVERESTORE-ASYNC-0010

DELAY 10000

START_TESTCASE MTP-SBE-ACTIVERESTORE-ASYNC-0020
//! @SYMTestCaseID MTP-SBE-ACTIVERESTORE-ASYNC-0020
//! @SYMTestCaseDesc Do Proxy active-restore for specified data owner asynchronously
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority normal
//! @SYMTestActions Do Proxy active-restore for specified data owner asynchronously
//! @SYMTestExpectedResults Restore succeeds
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestRestoreAsync z:\testdata\scripts\sbetestdata\test.ini ACTIVE_RESTORE_0020
END_TESTCASE MTP-SBE-ACTIVERESTORE-ASYNC-0020

DELAY 10000

START_TESTCASE MTP-SBE-ACTIVERESTORE-ASYNC-0030
//! @SYMTestCaseID MTP-SBE-ACTIVERESTORE-ASYNC-0030
//! @SYMTestCaseDesc Do Incremental active-restore for specified data owner asynchronously
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority normal
//! @SYMTestActions Do Incremental active-restore for specified data owner asynchronously 
//! @SYMTestExpectedResults Restore succeeds
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestRestoreAsync z:\testdata\scripts\sbetestdata\test.ini ACTIVE_RESTORE_0030
END_TESTCASE MTP-SBE-ACTIVERESTORE-ASYNC-0030

DELAY 10000

START_TESTCASE MTP-SBE-ACTIVERESTORE-ASYNC-0040
//! @SYMTestCaseID MTP-SBE-ACTIVERESTORE-ASYNC-0040
//! @SYMTestCaseDesc Do active-restore asynchronously for a data owner whose executable file is missing
//! @SYMPREQ 2492
//! @SYMTestStatus Released
//! @SYMTestPriority normal
//! @SYMTestActions Do active-restore asynchronously for a data owner whose executable file is missing 
//! @SYMTestExpectedResults Restore fails with error code 5
//! @SYMTestType CIT
RUN_TEST_STEP 300 BURTestServer TestRestoreAsync z:\testdata\scripts\sbetestdata\test.ini ACTIVE_RESTORE_0040
END_TESTCASE MTP-SBE-ACTIVERESTORE-ASYNC-0040

DELAY 10000